// ─── Spring physics animations ─────────────────────────────────────────────
export { DropSettle }       from './spring/DropSettle'
export { RiseOvershoot }    from './spring/RiseOvershoot'
export { GravityBounce }    from './spring/GravityBounce'
export { ExplodeFormation } from './spring/ExplodeFormation'
export { CenterBurst }      from './spring/CenterBurst'
export { Repulsion }        from './spring/Repulsion'
export { MagneticPull }     from './spring/MagneticPull'
export { SpringKerning }    from './spring/SpringKerning'
export { DragRelease }      from './spring/DragRelease'
export { GravityWell }      from './spring/GravityWell'
export { ThermalNoise }     from './spring/ThermalNoise'
export { Breathing }        from './spring/Breathing'
export { OrbitalDrift }     from './spring/OrbitalDrift'
export { WeightWave }       from './spring/WeightWave'
export { Pendulum }         from './spring/Pendulum'
export { Shockwave }        from './spring/Shockwave'
export { WaveCascade }      from './spring/WaveCascade'
export { JellyHover }       from './spring/JellyHover'
export { ScatterReturn }    from './spring/ScatterReturn'
export { DominoFall }       from './spring/DominoFall'

// ─── CSS transition animations ─────────────────────────────────────────────
export { FadeUp }       from './text/FadeUp'
export { BlurIn }       from './text/BlurIn'
export { ScaleBounce }  from './text/ScaleBounce'
export { SlideRight }   from './text/SlideRight'
export { Wave }         from './text/Wave'
export { FlipX }        from './text/FlipX'
export { FlipY }        from './text/FlipY'
export { Typewriter }   from './text/Typewriter'
export { Scramble }     from './text/Scramble'
export { Glitch }       from './text/Glitch'
export { ColorSweep }   from './text/ColorSweep'
export { CenterOut }    from './text/CenterOut'
export { FallDown }     from './text/FallDown'
export { Rtl }          from './text/Rtl'
export { NeonPulse }    from './text/NeonPulse'
export { ElasticSnap }  from './text/ElasticSnap'
export { RotateIn }     from './text/RotateIn'
export { Anticipate }   from './text/Anticipate'
export { StaggerFade }  from './text/StaggerFade'
export { RandomRain }   from './text/RandomRain'

// ─── Shared prop types ─────────────────────────────────────────────────────
export type { SpringAnimationProps } from './spring/shared'
export type { TextAnimationProps }   from './text/shared'
